# Generated by Django 4.2.3 on 2024-02-25 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_book_book_add_time_alter_issueditem_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_add_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
