# Generated by Django 4.2.3 on 2024-03-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueditem',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.student'),
        ),
    ]
